---
title: "Getting Started with R"
author: "Your Name"
date: "2024-08-19"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

# **1 Getting Started with R**

## **1.1 Overview**

#### **Why Learn R?**

Over the last decade, the pharmaceutical industry has been moving away from SAS, exploring other programming languages like R, Python, and Julia. In this time, R development has overcome its initial hurdles. Specifically, R can run in parallel; it can overcome memory limitations; and there are methods of working with big data sets. One of the things that R is best known for is its highly customization graphical capabilities.

Along with all of this R is free and open source, meaning that anyone can contribute to the publicly available tools within R. Even though R is free, the RStudio company offers free and fee-based services to support R use at scale.

#### **How is R different from SAS?**

|                                    |                                     |                                                                                                                                          |
|------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                    |                                     | Differences Between SAS and R                                                                                                            |
| SAS                                | R                                   | Notes                                                                                                                                    |
| Proprietary                        | Open Source                         | SAS subscriptions support cutting edge development and quality assurance; while R relies on volunteers, grants, and corporate investment |
| Licenses                           | Packages                            | SAS Licenses offer various sets of tools; R Packages are similar                                                                         |
| Case insensitive                   | Case sensitive                      | All syntax in R is case sensitive                                                                                                        |
| Light memory usage                 | Heavy memory usage                  | SAS generally operates based on disk write speed, but R operates on memory speed                                                         |
| Performance limited by write speed | Performance limited by memory speed |                                                                                                                                          |
| Automatic log generation           | No automatic log                    | R requires 3rd party packages like `logr` or `tidylog`                                                                                   |
| Datasets                           | Vectors and Data Frames             | A dataset is a table, but a dataframe is equivalent to a list of vectors                                                                 |
| Data libraries                     | Projects                            | Data Libraries in SAS and RStudio Projects help maintain workind directories and file structure                                          |
| Formats                            | Formatting                          | SAS has formats, informats, and lengths; but R has no such equivalent                                                                    |
| ODS                                | R Markdown and other packages       | SAS ODS adjusts how results are displayed and stored, the `rmarkdown` package offers similar report customization                        |

## **1.2 History of R**

In this lesson, we give a brief overview of the history of `R`.

**R Foundation**

S was created in 1976 at Bell Labs by John Chambers, Richard Becker, and Allan Wilks. The languages S, New S, S4, and S+ were all predecessors to R

R was created in 1995 at the University of Auckland, New Zealand by Ross Ihaka and Robert Gentlemen

-   Version 1.0 was released to the public in 2000

-   The ‘Core R Group’ was formed in 1997

-   The ‘R Foundation’ was formed in 2003

-   The ‘R Consortium’ was formed in 2015 as a joint collaboration to further R development

    -   Members include Microsoft, Google, IBM, Oracle, RStudio, and many more

**Microsoft Machine Learning Services**

-   Established as Revolution Analytics in 2007, specializing in big data

-   Acquired by Microsoft in 2015

-   Now part of Azure Machine Learning Platform

**RStudio**

RStudio was founded in 2009 with the intention of providing a graphical user interface for R. Packages created by RStudio share a common philosophy of package development, along with function design and usage.

**The Tidyverse**

The Tidyverse was created in 2016 by Hadley Wickham and collaborators at RStudio.

-   The tidyverse started with ggplot2 in 2008

-   Has grown to contain dozens of packages that share the RStudio design and philosophy

-   Includes ggplot2, dplyr, tibble, and many more

## **1.3 RStudio Tour**

In this lesson, we give a tour of the RStudio IDE, including:

-   Script Editor

-   Console Panel

-   Environment Panel

-   Miscellaneous Panel

-   RStudio Keyboard Shortcuts

## **1.4 R Resource Tour**

In this lesson, we provide an overview of the various online resources available for helping you to learn and use R.

|                |                                                |
|----------------|------------------------------------------------|
|                | R Resources                                    |
| Resource       | Link                                           |
| Bioconductor   | <https://bioconductor.org/>                    |
| CRAN           | <https://cran.r-project.org/>                  |
| GitHub         | <https://github.com/>                          |
| Hadley Wickham | <http://hadley.nz/>                            |
| Microsoft MRAN | <https://mran.microsoft.com/>                  |
| R Consortium   | <https://www.r-consortium.org/>                |
| R Studio       | <https://rstudio.com/>                         |
| R              | <https://www.r-project.org/>                   |
| Tidyverse      | <https://www.tidyverse.org/>                   |
| R Bloggers     | <https://www.r-bloggers.com/>                  |
| Stack Overflow | <https://stackoverflow.com/questions/tagged/r> |
| Twitter        | <https://twitter.com/hashtag/rstats>           |
