# **Objectives**

Use Tidyverse functions to perform summary operations on a data frame.

# **Exercise**

1.  Launch **Learning Lab** or Local environment.

2.  Open **RStudio** and start a new script.

3.  Read in the `data/vs_analysis.rds` file that you created in the previous lesson. Name your data frame `vs_analysis`.

4.  Use the [`summary()`](https://rdrr.io/r/base/summary.html) function on the `Diff_fromLastMAP` variable. You should get the following output to the console.

    | Min.     | 1st Qu. | Median | Mean    | 3rd Qu. | Max.    | NA’s |
    |----------|---------|--------|---------|---------|---------|------|
    | -26.7000 | -5.4000 | 0.0000 | -0.1684 | 4.6250  | 29.3000 | 94   |

5.  Reproduce these results by using a `summarize()` function. The following result should be printed to the console when you are finished.

    |     | min     | firstq  | median  | mean    | thirdq  | max     | NAs     |
    |-----|---------|---------|---------|---------|---------|---------|---------|
    |     | \<dbl\> | \<dbl\> | \<dbl\> | \<dbl\> | \<dbl\> | \<dbl\> | \<int\> |
    |     | -26.7   | -5.4    | 0       | -0.1684 | 4.62    | 29.3    | 94      |

6.  We will now summarize the `MAP` variable in the `vs_analysis` data frame. Use the `summarize()` function to create a summary of MAP for subject “01-051” that contains the following statistics: `# of non-missing, # of missing, minimum, median, mean, maximum, first value, second value, last value`. The results should be saved in a data frame named `vsa_01_051`. The following result should be printed when you run `print(vsa_01_051)`.

    |     | n_MAP   | nmiss_MAP | min_MAP | median_MAP | mean_MAP | max_MAP | first_MAP | second_MAP | last_MAP |
    |-----|---------|-----------|---------|------------|----------|---------|-----------|------------|----------|
    |     | \<int\> | \<int\>   | \<dbl\> | \<dbl\>    | \<dbl\>  | \<dbl\> | \<dbl\>   | \<dbl\>    | \<dbl\>  |
    |     | 7       | 1         | 86.7    | 98.7       | 95.5     | 107\.   | 107\.     | NA         | 99.3     |

7.  Create a data frame named `deciles` which contains the `deciles` for the variables `PULSE`, `TempF`, and `MAP` from the data frame `vs_analysis`. When the `deciles` data frame is printed to the console, it should look like the following:

    |     | Decile  | Pulse_Deciles | TempF_Deciles | MAP_Deciles |
    |-----|---------|---------------|---------------|-------------|
    |     | \<chr\> | \<dbl\>       | \<dbl\>       | \<dbl\>     |
    | 1   | 10%     | 62            | 96.8          | 80.2        |
    | 2   | 20%     | 66            | 97.0          | 86          |
    | 3   | 30%     | 68            | 97.2          | 88          |
    | 4   | 40%     | 72            | 97.2          | 91.3        |
    | 5   | 50%     | 72            | 97.3          | 93.3        |
    | 6   | 60%     | 76            | 97.5          | 96          |
    | 7   | 70%     | 78            | 97.7          | 98.7        |
    | 8   | 80%     | 80            | 97.9          | 102\.       |
    | 9   | 90%     | 88            | 98.3          | 107\.       |

8.  Save your R script and name it *Tidyverse_Summaries.R*.

# **Objectives**

Use Tidyverse functions to perform summary operations on a data frame.

# **Exercise**

1.  Launch **Learning Lab** or Local environment.

2.  Open **RStudio** and the script from the previous exercise named *Tidyverse_Summaries.R*.

3.  Read in the `vs_analysis.rds` file that you created in the previous lesson. Name your data frame `vs_analysis`.

4.  We have two blood pressure variables. Summarize these using the `across()` function to find the mean of each. Write your code so that it doesn’t matter how many BP variables there are. What do you get? Is it helpful?

5.  How can use add the `na.rm` parameter to remove the missing values?

6.  We want to understand the distribution of temperature in Fahrenheit. Let’s follow these steps.

    a.  Create a list of the functions `min`, `median`, `mean`, and `max` to summarize the Fahrenheit temperature.

    b.  Now use the list and the `across()` function to get the summary. Name the variables as `Temp_F_min`, `Temp_F_median`, `Temp_F_mean`, `Temp_F_max`. When it runs, what do you get?

    c.  We can’t pass the `na.rm` parameter into the functions this way. Instead we will define our own functions within the the list. For example, replace `"min" = min` in the previous list with `"min" = function(x) min(x,na.rm=TRUE)`. As you can see, this way we are able to call the [`min()`](https://rdrr.io/r/base/Extremes.html) function with the parameters we want. Make a similar replacement for the other functions in the list and then re-run the summarization.

7.  Save your R script.
