---
title: "Shiny and R Markdown"
author: "Anova Groups"
date: "2024-08-19"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=TRUE
  , warning=FALSE
  , message=FALSE
  , tidy = TRUE
  , tidy.opts = list(width.cutoff = 60))

```

# **11 Shiny and R Markdown**

## **11.1 Introduction**

In this course we give introductions to `R Markdown`, Shiny, along with HTML and CSS. `R Markdown` is a markdown based system of creating repeatable reports allowing for R code to be run side by side with English text based explanations and comments. In fact, this document you are reading now is created using `R Markdown`. Shiny is an HTML based system of creating an interactive application for data exploration and visualization. This course talks about using both of these concepts independently of each other, and how to use them together to compliment each other.

## **11.2 Introduction to HTML**

This lesson gives an introduction to HTML. We cover this here because `R Markdown` can easily include HTML customization. It’ll be important to know some basics of HTML if you want to modify your `R Markdown` documents or Shiny applications beyond the what default templates provide.

Visit the [W3 Schools](https://www.w3schools.com/html) homepage to browse the HTML documentation.

## **11.3 HTML and R Markdown**

This lesson gives an introduction to `R Markdown` along with using HTML to modify a `R Markdown` document beyond the default markdown formatting.

`R Markdown` is useful for creating documents that can display R code and output along with formatted text. Output can be stored as either HTML, DOCX, PDF, or RTF. In the video, we cover the basics of creating a `R Markdown` script, and giving a tour of the RStudio options available when editing a `R Markdown` script.

Some notes:

-   You can find the `Markdown Quick Reference` in the RStudio Help menu

-   See the [free online book](https://bookdown.org/yihui/rmarkdown) for thorough examples for using `R Markdown`

## **11.4 Shiny and R Markdown**

This lesson starts to incorporate interactive Shiny elements in a `R Markdown` HTML document. We give a brief introduction to the `reactive` context concept in R. This is the environment that allows users to interact with an HTML document in an interactive and responsive way. `R Markdown` documents that make use of Shiny elements will no longer be portable, meaning these documents would need to be hosted on an external server if you want others to be able to interact with the document.

A majority of the functions from the `shiny` package are nothing more than templates for HTML code. So you have the choice of using the provided Shiny functions, or you can modify the HTML code to suit your needs.

This lesson covers only the basics of reactive output, utilizing simple text based output.

## **11.5 Shiny Output and R Markdown**

This lesson continues the previous lesson, this time including more complex reactive output.

There are five steps to be aware of when capturing user input and displaying results. The distinction lies between what is done on the HTML UI and what is done on the R server. Shiny creates two temporary global variables:

-   `input` contains information that comes from the user interface for use in the R computation server

-   `output` information that comes from the R computation server and pushes to the user interface browser

The five steps are:

1.  The selection input above is rendered in HTML on the user interface

2.  Create reactive context to capture user input ‘events’

3.  Create reactive context that depends on ‘events’ generated by user input

4.  Renders the plot and places it in the output ‘buffer’ temporarily

5.  Push rendered plot to user interface from output buffer

#### **Rendering Functions**

| Render Functions | Output Functions     | Use Case                              |
|-------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `renderText`     | `textOutput`         | Displays formatted text output        |
| `renderPrint`    | `verbatimTextOutput` | Displays formatted text output        |
| `renderPlot`     | `plotOutput`         | Displays base/ggplot2 plots           |
| `renderTable`    | `tableOutput`        | Displays table output                 |
| `renderImage`    | `imageOutput`        | Displays images from a file           |
| `renderUI`       | `uiOutput`           | Dynamically update the user interface |

## **11.6 Basic Shiny**

In this lesson, we talk about using Shiny without `R Markdown`.

Every `shiny` application file must be named `app.R`, and contain with the following application template. It is recommended to keep separate directories within your project directories to contain distinct Shiny applications.

``` r
library(shiny)  
ui     <- shiny::fluidPage() 
server <- function(input, output, session) {}  
shiny::shinyApp(ui, server)
```

A Shiny application requires connections between the UI and the Server portions of the script, so it is recommended to use informative headers and the the script outline feature of RStudio so that you can quickly jump back and forth, between different sections of the script.

The UI portion of the application contains all the areas that will be displayed and interacted with by the end user. The objects that capture user input will be stored in the `input` global variable that we talked about in the previous lesson. Then in the server portion of the script, the actual R processing will take place. Anything that is going to be returned to the UI is stored in the `output` global variable.

Remember to follow the five steps of capturing user input and displaying results.

## **11.7 Dynamic Shiny**

This lesson introduces the methods to dynamically adjust the user interface based on user input. This is done using the [`observeEvent()`](https://rdrr.io/pkg/shiny/man/observeEvent.html) function in combination with the `update*()` family of functions. The two functions [`renderUI()`](https://rdrr.io/pkg/shiny/man/renderUI.html) and [`uiOutput()`](https://rdrr.io/pkg/shiny/man/htmlOutput.html) allow for more complex use cases of altering the user interface.

## **11.8 Introduction to CSS**

This lesson provides a brief introduction to cascading style sheets, known as CSS. This is a standardized language for defining the styling of HTML. This includes color, size, space, borders, backgrounds, layouts, and more. Every element of an HTML page is determined by a default CSS template. Even basic knowledge of CSS allows for a wide variety of customization in the display of your R Markdown documents and Shiny Applications.

Bootstrap is the primary CSS template used by R Markdown and Shiny. Version 4 is the current standard, but Bootstrap Version 5 is in active development.

See the [W3 Schools](https://www.w3schools.com/CSS/css_syntax.asp) online documentation for more information, and visit the [Bootswatch](https://bootswatch.com/) website for pre-defined themes that you can use in your own documents and applications.

## **11.9 Custom Shiny**

In this lesson, we apply various CSS themes to a Shiny application. The `bslib` package provides us with the `bs_theme()` and `bs_themer()` functions to help us change the CSS styling of an existing application. While, the `thematic` package provides `themeatic_shiny()` to help us ensure all of our interactive graphics follow a similar theme.

Note that most Shiny functions have a `style` or `class` argument to allow you to more easily adjust the CSS arguments of the user interface element.

## **11.10 Wrap Up**

This course is merely an introduction to R Markdown and Shiny. The options to customize HTML, CSS, and JavaScript allow for any number of unique customizations to be made to your dynamic reports and Shiny applications. But the benefit of Shiny and R Markdown is that you don’t necessarily need to know HTML, CSS, or JavaScript to create a useful application or document.

Some additional topics that are worth exploring in Shiny are:

-   Debugging in Shiny

-   Testing and Optimizing Reactivity

-   Using Shiny Modules to Reuse UI / Server Definitions

-   Using Shiny Golem to Prepare Shiny for Use in Production

## **Useful Links**

-   [Using Shiny in RMarkdown](http://rmarkdown.rstudio.com/authoring_shiny.html)

-   [RStudio Shiny Tutorial](https://shiny.rstudio.com/tutorial/)

-   [RStudio Shiny Cheatsheet](https://rstudio.com/resources/cheatsheets/)

-   [RStudio Shiny Reference](https://shiny.rstudio.com/reference/shiny/1.6.0/)

-   [Mastering Shiny Book](https://mastering-shiny.org/)

    -   [Chapter on Tidyverse Evaluation in Shiny](https://mastering-shiny.org/action-tidy.html)
