#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#   http://shiny.rstudio.com/
#

library(shiny)
library(tidyverse)

adae <- readRDS("../data/adae.rds")

adae_filt <-
    adae %>%
    filter(AESEV != "MILD" & ADURN > 10)

subject_list <- unique(adae_filt$SUBJID)

# Define UI for application for Exercise 1.


# Define server logic required to prep data and show ae table.
# 1. The selection input is rendered in HTML on the user interface
# 2. Create reactive context to capture user input 'events'
# 3. Create reactive context that depends on 'events' generated by user input
# 4. Renders the object and places it in the output 'buffer' temporarily
# 5. Push rendered object to user interface from output buffer

server <- function(input, output) {

    # 1. Done in user interface section.
    # 2. Capture user events in reactive context.
    subject_selected_by_user <- reactive(input$selected_subject)

    # 3. Create reactive context that depends on 'events' generated by user input

    ae_datatable_to_display  <- reactive({
        adae %>%
            filter(SUBJID == input$selected_subject) %>%
            select(SUBJID, TRTA, AETERM, AESEV, AEREL, AESER, AEACN) %>%
            DT::datatable(options = list(pageLength = 10))
    })

    # 4. Render the object and place in output buffer
    output$ae_table_output <- DT::renderDataTable(ae_datatable_to_display())

}

# Run the application
shinyApp(ui = ui, server = server)
