# **Objectives**

Use Tidyverse functions to perform group operations on a data frame.

# **Exercise**

1.  Launch **Learning Lab** or Local environment.

2.  Open **RStudio** and start a new script.

3.  Read in the `adae.rds` file from the \_data directory within the course level directory into a data frame named `adae`.

4.  Create a data frame named `adae_headache` which only contains the variables `SITEID`, `SUBJID`, `TRTA`, `AESTDY`, and `AETERM`. Also `filter` data to only contains records where `AETERM` is equal to `"HEADACHE"`.

5.  Run the following code and examine the output sent to the console.

```         
adae_headache %>% group_by(TRTA) class(adae_headache)
```

6.  Given the results of the previous step, reflect on the following questions:

    -   Did the order of the data change after applying the `group_by()` function?

    -   Did the groups attribute stick with the data frame?

7.  Now run the following code and examine the output sent to the console.

```         
adae_headache <-    adae_headache %>%    group_by(TRTA)  class(adae_headache)
```

8.  Given the results of the previous step, reflect on the following questions:

    -   Did the groups attribute stick with the data frame this time?

    -   Would it make sense to use the `arrange()` function along with the `group_by()` function?

9.  Now run the following code and examine the output sent to the console.

``` r
adae_headache1st <-   adae_headache %>%   
group_by(TRTA) %>%   
slice_head(n = 1)  
adae_headache1st  
adae_headache1st <-   adae_headache %>%   
group_by(TRTA) %>%   
arrange(TRTA, SUBJID, AESTDY) %>%   
slice_head(n = 1)  
adae_headache1st  
class(adae_headache1st)
```

10. Given the results of the previous step, notice how you can use the `arrange()` function along with the `group_by()` function to get the appropriate first record based on sorted data. Does this feel like a first dot operation in SAS? Experiment simulating a last dot operation by using `slice_tail()`.

11. Save your R script and name it *Tidyverse_Group_Operations.R*.

# **Objectives**

Use Tidyverse functions to perform group operations on a data frame.

# **Exercise**

1.  Launch **Learning Lab** or Local environment.

2.  Open **RStudio** and the script from the last exercise.

3.  Read in the `adae.rds` file from the course level directory into a data frame named `adae`.

4.  Now that you know the `group_by()` function, how would you use it to get a table with counts for each Planned Treatment? Produce a table of counts grouping the table by TRT

5.  Let’s see now how many people stayed in the same treatment they were planned for. Do a count on combinations of both variables, `TRTP` and `TRTA`.

6.  Create a data frame named `adae_gb` from the `adae` data frame with the following requirements.

    -   Only keep the variables `TRTA`, `AEBODSYS`, `AETERM`, `SITEID`, `SUBJID`, `AESTDY`.

    -   Group by the variables `TRTA`, `AEBODSYS`, `AETERM`.

    -   Replace missing values for `TRTA` of `""` with `"NO ARM"`.

7.  Now create a data frame called `ae_stats` with the following requirements.

    -   Summarize the data calculating the following.

        -   How many subjects had each `AETERM`.

        -   What was the minimum, average, and maximum time to event (`AESTDY`). Please ignore NA values using the na.rm parameter on the summary statistic functions.

    -   Keep only `AETERM` records for which more than one subject had it.

    -   Sort the result by descending frequency.

    -   Sending `ae_stats` results to the console should look like the following output. Note: depending on how wide your console window is, the AEBODSYS and AETERM may or may not truncate as shown below.

        \# A tibble: 12 × 7 \# Groups: TRTA, AEBODSYS [10] TRTA AEBODSYS AETERM count_subj_w_ae min_time_to_event ave_time_to_event \<chr\> \<chr\> \<chr\> \<int\> \<dbl\> \<dbl\> 1 ARM A Nervous sys… HEADA… 4 2 88.9 2 ARM A Infections … URI 3 4 79.5 3 ARM B Infections … UPPER… 3 1 21.7 4 ARM B Nervous sys… HEADA… 3 7 18.2 5 ARM C Infections … COMMO… 3 -4 37 6 ARM C Nervous sys… HEADA… 3 2 41.4 7 ARM D Nervous sys… HEADA… 3 1 32.3 8 ARM B Gastrointes… DIARR… 2 -4 6.5 9 ARM B Infections … URI 2 5 34 10 ARM C Infections … URI 2 6 39.5 11 ARM D Gastrointes… TOOTH… 2 4 43 12 ARM D Investigati… DECRE… 2 42 42.5 \# ℹ 1 more variable: max_time_to_event \<dbl\>

<!-- -->

8.  Save your R script and name it *Tidyverse_Group_Operations.R*.

# **Objectives**

Use Tidyverse functions to perform group operations on a data frame.

# **Exercise**

1.  Launch **Learning Lab** or Local environment.

2.  Open **RStudio** and start a new script. Load the proper packages.

3.  Read in the SAS data set, **“bbc_adam_adlb.sas7bdat**, from the course level directory into a data frame named `bbc_adam`.

4.  There are variables in the data frame that are flags. They are denoted by `"FL"`. How many flag variables are there?

5.  Create a variable `flagchk` that counts the number of flags checked (`Y`) in each row. There are almost 12,000 records. You may want to sample the data frame (say, `n=100`) while you work out the code.

6.  When your code works, summarize the number of flags checked for each row. Which function did you use? Why?

7.  Save your R script and name it *Tidyverse_Group_By_Row.R*.

# 
