#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#   http://shiny.rstudio.com/
#

library(shiny)
library(tidyverse)

dm <- readRDS("../data/dm_r.rds") %>%
    select(SUBJID, ARM, SEX, BRTHDTC, AGE, RACE)

bmi <- readRDS("../data/BMI_analysis.rds") %>%
    mutate(SUBJID = substring(SUBJECT, 4, 7)) %>%
    select(SUBJID, WEIGHT, HEIGHT, BMI, ntile_BMI)

adae <- readRDS("../data/adae.rds")

adae_filt <-
    adae %>%
    filter(AEREL != "NOT RELATED")

subject_list <- unique(adae_filt$SUBJID)

# Define UI for application creates the AE listing
ui <- fluidPage(

    # Application title
    titlePanel("Data Explorer for Patients with an Adverse Event Not 'Not Related' to Drug"),

    # Sidebar with a drop down list for selecting SUBJID
    sidebarLayout(
        sidebarPanel(
            selectInput(
                inputId = 'selected_subject',
                label = "Select a Subject",
                choices = subject_list),
                width = 2
        ),

        # Show a plot of the generated distribution
        mainPanel(
            tabsetPanel(
                tabPanel(title = "DM",
                         shiny::h4("Demographic Information"),
                         DT::dataTableOutput("dm_table_output")),
                tabPanel(title = "BMI",
                         shiny::h4("BMI Information"),
                         DT::dataTableOutput("bmi_table_output")),
                tabPanel(title = "AE",
                         shiny::h4("Adverse Events Information"),
                         DT::dataTableOutput("ae_table_output"))
            ),
                 )
    )
)

# Define server logic required to prep data and show ae table.
# 1. The selection input is rendered in HTML on the user interface
# 2. Create reactive context to capture user input 'events'
# 3. Create reactive context that depends on 'events' generated by user input
# 4. Renders the object and places it in the output 'buffer' temporarily
# 5. Push rendered object to user interface from output buffer

server <- function(input, output) {

    # 1. Done in user interface section.
    # 2. Capture user events in reactive context.
    subject_selected_by_user <- reactive(input$selected_subject)

    # 3. Create reactive context that depends on 'events' generated by user input

    dm_datatable_to_display  <- reactive({
        dm %>%
            filter(SUBJID == input$selected_subject)  %>%
            DT::datatable(options = list(pageLength = 1))
    })

    bmi_datatable_to_display  <- reactive({
        bmi %>%
            filter(SUBJID == input$selected_subject)  %>%
        DT::datatable(options = list(pageLength = 1))
    })


    ae_datatable_to_display  <- reactive({
        adae %>%
            filter(SUBJID == input$selected_subject) %>%
            select(SUBJID, TRTA, AETERM, AESEV, AEREL, AESER, AEACN) %>%
            DT::datatable(options = list(pageLength = 10))
    })

    # 4. Render the object and place in output buffer
    output$dm_table_output <- DT::renderDataTable(dm_datatable_to_display())
    output$bmi_table_output <- DT::renderDataTable(bmi_datatable_to_display())
    output$ae_table_output <- DT::renderDataTable(ae_datatable_to_display())

}

# Run the application
shinyApp(ui = ui, server = server)
