# **Objective**

Become comfortable with various string operators.

## **Exercise 1**

1.  Launch Learning Lab or Local environment.

2.  Open RStudio and start a new script and set your working directory to the course level directory using the Session \> Set Working Directory menu item.

3.  Notice the [`setwd()`](https://rdrr.io/r/base/getwd.html) function in the console. Copy and paste it to your program so that when you run the program in future sessions, the working directory is automatically set.

4.  Create a variable, `data_directory` with the value `data`.

5.  Create a variable, `data_frame`, with the value `invdata_new.rds`.

6.  Determine the length of each of the two variables `data_directory` and `data_frame`.

7.  Use the [`file.path()`](https://rdrr.io/r/base/file.path.html) function to create the full path for your R script, `data_path`.

8.  What do you expect the length of `data_path` to be? Check the length to confirm your understanding.

9.  Save your R script and name it `String_Operations.R`.

## **Exercise 2**

1.  Launch Learning Lab or Local environment.

2.  Open the RStudio script from the last lesson, `String_Operations.R`. Run it to set your working directory to the course level directory and create the `data_path` variable.

3.  Use the `data_path` variable to read in the `invdata_new.rds` R data frame from the course level directory. Name the data frame `invdata`. *Note, we created this data frame in previous exercise.*

4.  Use the paste() function to create a vector with each element showing the raw data like the following example for the first record:

    -   `"1001, M, 23, AZO, Kalamazoo"`

5.  Copy and modify the previous line to make a vector of length one with a newline character between each element of the vector. How would you output that vector so that it looks like the following?

    ```         
      1001, M, 23, AZO, Kalamazoo    
      1002, F, 12, AZO, Kalamazoo    
      1003, M, 10, SFO, San Francisco    
      1004, M, 3, ORD, Chicago    
      1005, F, 2, ORD, Chicago
    ```

6.  Use the [`ifelse()`](https://rdrr.io/r/base/ifelse.html) conditional logic function within the [`paste0()`](https://rdrr.io/r/base/paste.html) or [`paste()`](https://rdrr.io/r/base/paste.html) function to add a variable named `inv_bio` that combines variables and constant text into a sentence like the following example for the first record:

    -   `Investigator 1001 is a male, with 23 years experience, and is located in Kalamazoo.`

7.  Save your R script.

## **Exercise 3**

1.  Launch Learning Lab or Local environment.

2.  Open RStudio and your script `String_Operations.R`. Run it to set your working directory.

3.  Consider the `inv_bio` we made in the previous exercise that contained sentences about the Investigators. The first record looked like this:

    -   `Investigator 1001 is a male, with 23 years experience, and is located in Kalamazoo.`

    Instead of the word *and*, we decided to use an ampersand symbol. Use the [`sub()`](https://rdrr.io/r/base/grep.html) or [`gsub()`](https://rdrr.io/r/base/grep.html) function to replace ’ `and` ’ with ’ `&` ’ in variable we just created.

4.  Now we want to change the word *is* to *was* for each record. Which function, [`sub()`](https://rdrr.io/r/base/grep.html) or [`gsub()`](https://rdrr.io/r/base/grep.html), can replace all occurrences of *is* at once? Use that function to do so.

5.  Read in the `data/raw_vitals.rds` data frame from the course level directory and name it `raw_vs`.

6.  The `raw_vs` has a variable named `SUBJECT` that is a two digit `siteid`, followed by a hyphen, followed by a three digit `subjectID`. From the first two characters of the `SUBJECT` variable, create a variable named `site_id` which is a numeric site number. From the last three characters create a numeric variable named `subj_id` which is a numeric `subjectID` variable.

7.  Using our `invdata` data frame. Consider the total years of experience of the investigator team. Each investigator’s years of experience would count towards the total years of experience for that team. Add a variable to `invdata` named `pct_ye` that is a % of years of experience using the sum of all investigators years of experience as the denominator. Use the `format` and `paste0` functions to make it look like `xx.x%`. i.e. `34.0%`.

8.  Define the following variable in your session.

    -   `aecsv <- "headache, vOMITing, nAUsEA, CHILLS, vertigo"`

9.  Use the [`strsplit()`](https://rdrr.io/r/base/strsplit.html) function to turn the comma separated variable values in `aecsv` into a list object named `aelist`.

10. Change the list into a vector named `aevector` using the [`unlist()`](https://rdrr.io/r/base/unlist.html) function and eliminate the leading blanks.

11. Change the `aevector` vector elements into proper case (first character upper case and the rest of the word lower case).

12. Save your R script.
