# **Objectives**

Comprehensive review of R Language Foundation I & II concepts.

# **Exercise**

1.  Launch **Learning Lab** or Local environment.

2.  In this lesson, we will be leveraging an existing R script as shown in the video and modifying it per the requirements below.

3.  Open the `RLang2_Capstone_Training_R_Code.R` script in **RStudio**.

4.  Requirements:

    a.  Work through the program from the video and execute it step by step to understand how it works and what it produces.

    b.  Copy the `RLang2_Capstone_Exercise_Formats.R` file from the lesson level directory to your course level directory. Rename it formats.R.

    c.  Read in the `dm.rds` data frame from the course level directory. We will use it as the data source for the `demog` table. Name the data frame `df`.

    d.  Subset the `df` data frame to keep only the variables `SUBJID`, `ARM`, `AGE`, and `SEX` and only records where the `ARM` is not equal to `"SCREEN FAILURE"`.

    e.  Create a function named `arm_fmt()` which returns `"Placebo"` if `ARM` equals `"ARM A"` and `"Active"` if `ARM` is a different `ARM` value. Add the function to formats.R. *Note, be sure to re-source the file formats.R*

    f.  Use that function to create a new variable called `ReportARM` on the data frame `df`.

    g.  Using the data frame you created and the existing Training R Code from the video, produce a `demog` table containing statistics for each `ReportARM` variable.

    h.  The resulting `demog` table should look like the table below when examining with the [`View()`](https://rdrr.io/r/utils/View.html) function.

        +-----------+----------------+-------------------+--------------------+
        | **stub**\ | **labels**\    | **stats_active**\ | **stats_placebo**\ |
        | Measure   | Statistics     | Active(N=65)      | Placebo(N=20)      |
        +===========+================+===================+====================+
        | Age       | n / \# missing | 65 / 0            | 20 / 0             |
        +-----------+----------------+-------------------+--------------------+
        |           | Mean           | 47.7              | 53.1               |
        +-----------+----------------+-------------------+--------------------+
        |           | Median         | 46.0              | 52.5               |
        +-----------+----------------+-------------------+--------------------+
        |           | Range          | 19 - 75           | 31 - 73            |
        +-----------+----------------+-------------------+--------------------+
        |           |                |                   |                    |
        +-----------+----------------+-------------------+--------------------+
        | Age Group | n / \# missing | 65 / 0            | 20 / 0             |
        +-----------+----------------+-------------------+--------------------+
        |           | \< 18          | 0 (0.0%)          | 0 (0.0%)           |
        +-----------+----------------+-------------------+--------------------+
        |           | 18 - 23        | 5 (7.7%)          | 0 (0.0%)           |
        +-----------+----------------+-------------------+--------------------+
        |           | 24 - 44        | 19 (29.2%)        | 4 (20.0%)          |
        +-----------+----------------+-------------------+--------------------+
        |           | 45 - 59        | 25 (38.5%)        | 10 (50.0%)         |
        +-----------+----------------+-------------------+--------------------+
        |           | \>= 60         | 16 (24.6%)        | 6 (30.0%)          |
        +-----------+----------------+-------------------+--------------------+
        |           |                |                   |                    |
        +-----------+----------------+-------------------+--------------------+
        | Sex       | n / \# missing | 65 / 0            | 20 / 0             |
        +-----------+----------------+-------------------+--------------------+
        |           | Female         | 27 (41.5%)        | 5 (25.0%)          |
        +-----------+----------------+-------------------+--------------------+
        |           | Male           | 38 (58.5%)        | 15 (75.0%)         |
        +-----------+----------------+-------------------+--------------------+

5.  Save and close your R script.
